In [18]:
import pandas as pd

In [19]:
data=pd.read_csv("/content/data_for_gradient.csv")

In [20]:
data.head()

x      y
0  3.0   8.50
1  3.3   9.16
2  4.0  10.70
3  2.3   6.96
4  4.0  10.70

In [21]:
import numpy as np
x=np.array(data["x"])
y=np.array(data["y"])

In [22]:
import random

In [23]:
w0=random.random()
w1=random.random()

In [24]:
w0,w1

(0.6184951261786026, 0.6077685461308823)

In [25]:
yp=w0+w1*x

In [26]:
y

array([ 8.5  ,  9.16 , 10.7  ,  6.96 , 10.7  , 12.9  ,  6.08 ,  6.3  ,
        9.16 , 10.48 , 10.92 , 11.36 , 11.58 , 12.46 ,  6.3  ,  6.96 ,
        9.16 ,  9.182,  9.38 , 11.14 ,  4.54 ,  9.16 ,  9.38 ,  4.54 ,
       11.8  , 14.   , 16.42 , 21.7  , 21.26 , 20.6  , 22.14 , 21.48 ])

In [27]:
yp

array([2.44180076, 2.62413133, 3.04956931, 2.01636278, 3.04956931,
       3.65733786, 1.77325536, 1.83403222, 2.62413133, 2.98879246,
       3.11034617, 3.23189987, 3.29267673, 3.53578415, 1.83403222,
       2.01636278, 2.62413133, 2.63020901, 2.68490818, 3.17112302,
       1.34781738, 2.62413133, 2.68490818, 1.34781738, 3.35345358,
       3.96122213, 4.62976753, 6.08841204, 5.96685833, 5.78452777,
       6.20996575, 6.02763519])

In [28]:
Loss=1/len(x)*sum((yp-y)**2)
Loss

80.19063072995553

In [34]:
alpha=.01
k=0
w0=random.random()
w1=random.random()

while(k<20):
  print(w0,w1)
  yp=w0+w1*x
  Loss=1/len(x)*sum((yp-y)**2)
  print(Loss)
  w0=w0-alpha*(2/len(x)*sum(yp-y))
  w1=w1-alpha*(2/len(x)*sum((yp-y)*x))
  k=k+1

0.7218944606071716 0.7595541194863227
65.90894438139995
0.8705142821838749 1.5531202423296704
16.882566008487245
0.9472652885014384 1.952943010426872
4.415858438290391
0.9877691617449117 2.1542233824678894
1.2449926961566349
1.0099880472233793 2.255390782937522
0.4377397533161048
1.0229793277427548 2.306077914061177
0.23147849083576846
1.0313101892865009 2.3313118941837416
0.17803653072802286
1.0372836509876062 2.3437125583429115
0.16345939410561766
1.0420610332932205 2.34964341051235
0.1587724123702927
1.046227958780937 2.3523132206864292
0.15660828241101749
1.0500797561768485 2.3533399948308165
0.15509369171742524
1.0537653743770936 2.353539601496231
0.1537522561429427
1.057359950612151 2.3533234341492486
0.15246278165028976
1.0609014027013628 2.3528989310717594
0.15119438705499735
1.0644088805753493 2.352370686849149
0.14993915508796435
1.0678920703949577 2.351791437499755
0.14869500793438098
1.0713558861226267 2.3511877695556804
0.1474613530834942
1.074802835232062 2.35057308378066

In [35]:
w0,w1

(1.0850526646821117, 2.34871533743421)

In [36]:
yp=w0+w1*x

In [37]:
yp

array([ 8.13119868,  8.83581328, 10.47991401,  6.48709794, 10.47991401,
       12.82862935,  5.54761181,  5.78248334,  8.83581328, 10.24504248,
       10.71478555, 11.18452862, 11.41940015, 12.35888628,  5.78248334,
        6.48709794,  8.83581328,  8.85930043,  9.07068481, 10.94965708,
        3.90351107,  8.83581328,  9.07068481,  3.90351107, 11.65427168,
       14.00298702, 16.58657389, 22.2234907 , 21.75374763, 21.04913303,
       22.69323377, 21.98861917])

In [38]:
y

array([ 8.5  ,  9.16 , 10.7  ,  6.96 , 10.7  , 12.9  ,  6.08 ,  6.3  ,
        9.16 , 10.48 , 10.92 , 11.36 , 11.58 , 12.46 ,  6.3  ,  6.96 ,
        9.16 ,  9.182,  9.38 , 11.14 ,  4.54 ,  9.16 ,  9.38 ,  4.54 ,
       11.8  , 14.   , 16.42 , 21.7  , 21.26 , 20.6  , 22.14 , 21.48 ])